FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy and install requirements
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the common directory
COPY common /app/common

# Copy the application code
COPY . /app/

# Expose the port and run the application
ARG APP_ENTRYPOINT=app.main:app
ENV APP_ENTRYPOINT=${APP_ENTRYPOINT}
EXPOSE 8080
CMD ["sh", "-c", "uvicorn $APP_ENTRYPOINT --host 0.0.0.0 --port 8080"]
