steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - -c
  - |
    cp requirements.txt bugminer-service/requirements.txt
    cp -r common bugminer-service/
    cp requirements.txt code_analysis_service/requirements.txt
    cp -r common code_analysis_service/
    cp requirements.txt evaluator-service/requirements.txt
    cp -r common evaluator-service/
    cp requirements.txt fhir-service/requirements.txt
    cp -r common fhir-service/
    cp requirements.txt test-generator-service/requirements.txt
    cp -r common test-generator-service/
- name: 'gcr.io/cloud-builders/docker'
  dir: 'bugminer-service'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/bugminer-service', '.', '-f', '../Dockerfile.python']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'code_analysis_service'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/code-analysis-service', '--build-arg', 'APP_ENTRYPOINT=main:app', '.', '-f', '../Dockerfile.python']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'evaluator-service'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/evaluator-service', '.', '-f', '../Dockerfile.python']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'fhir-service'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fhir-service', '.', '-f', '../Dockerfile.python']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'test-generator-service'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/test-generator-service', '.', '-f', '../Dockerfile.python']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/bugminer-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/code-analysis-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/evaluator-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/fhir-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/test-generator-service']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'bugminer-service', '--image', 'gcr.io/$PROJECT_ID/bugminer-service', '--region', 'us-central1', '--platform', 'managed', '--quiet', '--allow-unauthenticated']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'code-analysis-service', '--image', 'gcr.io/$PROJECT_ID/code-analysis-service', '--region', 'us-central1', '--platform', 'managed', '--quiet', '--allow-unauthenticated']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'evaluator-service', '--image', 'gcr.io/$PROJECT_ID/evaluator-service', '--region', 'us-central1', '--platform', 'managed', '--quiet', '--allow-unauthenticated']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'fhir-service', '--image', 'gcr.io/$PROJECT_ID/fhir-service', '--region', 'us-central1', '--platform', 'managed', '--quiet', '--allow-unauthenticated']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'test-generator-service', '--image', 'gcr.io/$PROJECT_ID/test-generator-service', '--region', 'us-central1', '--platform', 'managed', '--quiet', '--allow-unauthenticated']
images:
- 'gcr.io/$PROJECT_ID/bugminer-service'
- 'gcr.io/$PROJECT_ID/code-analysis-service'
- 'gcr.io/$PROJECT_ID/evaluator-service'
- 'gcr.io/$PROJECT_ID/fhir-service'
- 'gcr.io/$PROJECT_ID/test-generator-service'
