apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: healthqagenagent
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      serviceAccountName: healthqa-service-account
      containers:
        - image: gcr.io/${PROJECT_ID}/healthqagenagent:latest
          ports:
            - containerPort: 8080
          env:
            - name: PROJECT_ID
              value: "${PROJECT_ID}"
            - name: REGION
              value: "${REGION}"
            - name: VERTEX_LOCATION
              value: "${VERTEX_LOCATION}"
            - name: STORAGE_BUCKET_NAME
              value: "${STORAGE_BUCKET_NAME}"
            - name: ENVIRONMENT
              value: "production"
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          concurrency: 80
          timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100

