from common.models import Requirement
from agents.test_generator import TestGeneratorAgent


def test_plan_and_generate_intent():
    tg = TestGeneratorAgent()
    req = Requirement(title="Ensure patient lookup")
    intents = tg.plan_tests([], [req], [])
    assert len(intents) == 1
    gen = tg.generate_test(intents[0])
    assert "autogenerated test" in gen.code
    # Ensure Hindi comment present
    assert "हिंदी" in gen.code
